name: Python CodeGuru Reviewer

on:
  push:
    branches: [main]

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          users: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Configure AWS Credentials
          users: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_ACESS_KEY }}
            aws-region: us-east-1

        - name: CodeGuru Reviewer
          users: aws-actions/codeguru-reviewer@v1.1
          with:
            build_path: target
            s3_bucket: codeguru-reviewer-arash

